### ISSUE TITLE
Ios implementaton

### ISSUE THREAD

**Issue by bilalswiftsolutions** [seididieci/capacitor-backround-geolocation#21] opened 2021-08-13 03:33 UTC
does this package provide ios implementation or still not able to do that? What we need to do for ios ?

**Comment by seididieci** [comment] 2021-08-16 07:25
This is a duplicate of #16 
At the moment I have no spare time to develop the iOS part, but if you wish and can contribute you're welcome...

**Closed as completed** 2021-08-16 07:25 UTC
